steps:
- id: 'master'
  name: 'hashicorp/terraform:1.0.2'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "master"
      echo "***********************"
- id: 'tf init'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.2'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 


# [START tf-apply]
- id: 'tf apply'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
