steps:

# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.2'
  entrypoint: 'sh'
  args: 
  - '-c'


# [START tf-plan]
- id: 'tf plan'
  entrypoint: 'sh'
  args: 
  - '-c'


# [START tf-apply]
- id: 'tf apply'
  entrypoint: 'sh'
  args: 
  - '-c'

